#! /bin/sh

set -e

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

sed -i 's|$|,keyscript=/sbin/ykluks-keyscript|' /cryptroot/crypttab

exit 0
